services:
  server:
    build: ./server
    ports:
      - "8000:443"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: on-failure
    networks:
      - pasco

  client:
    build: ./client
    ports:
      - "5173:443"
    depends_on:
      - server
    networks:
      - pasco

  db:
    image: postgres:16.0-alpine3.18
    volumes:
      - pasco:/var/lib/postgresql
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5432:5432"
    networks:
      - pasco
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "pasco" ]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080
    networks:
      - pasco
    depends_on:
      db:
        condition: service_healthy

  migrate:
    image: migrate/migrate
    env_file:
      - .env
    networks:
      - pasco
    volumes:
      - ./server/migrations:/migrations
    command: [ "-path", "/migrations", "-database", "$DATABASE_URL", "up" ]
    depends_on:
      db:
        condition: service_healthy

networks:
  pasco:


volumes:
  pasco:
